### ISSUE TITLE
Gap + vertikální padding

### ISSUE THREAD

**Issue by h0n24** [kostohryzova/Vizitka#1]
Ukázka kódu (zakomentované jsou vaše předchozí hodnoty):

```css
img {
  width: 23px;
  height: 23px;
  vertical-align: middle;
  margin-right: 1rem;
  /* opacity: 0.5; */
}
.vizitka {
  display: flex;
  align-items: center;
  background-color: #fff6d6;
  border: 2px solid #ddd;
  border-radius: 15px;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  padding: 20px;
  width: 520px;
  height: 220px;
  /* preferujte gap u rodiče před marginy u každého z dětí */
  gap: 20px;
}
h1,
h2 {
  margin: 0;
}
h1 {
  font-family: lora;
  font-style: italic;
  /* margin-left: 15px; */
  /* margin-bottom: 5px; */
  color: #3c2b21;
  margin-bottom: 0.25rem;
}
p {
  font-family: lora;
  font-weight: 400;
  font-size: 16px;
  color: #3c2b21;
  /* margin-left: 30px; */
  margin: 0;
  margin-bottom: 0.5rem;
}
h2 {
  font-family: lora;
  font-style: italic;
  font-size: 16px;
  color: #3c2b21;
  /* margin-left: 15px; */
  /* margin-top: 10px; */
  margin-bottom: 1.5rem;
}
.logo {
  width: 200px;
  height: 200px;
  margin-right: 5px;
  margin-left: -15px;
  object-fit: cover;
}
.info {
  flex: 1;
}

p img {
/* snížení kontrastu na stejnou hodnotu jako u hlavního obrázku 
-> tohle by bylo asi lepší udělat v nějakém grafickém editoru než v css (kvůli performance) */
    filter: contrast(0.5);
}
```
